import type { Config } from 'tailwindcss'

export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'on-tertiary': '#ffffff',
        'on-error-container': '#93000a',
        'surface-container': '#f5eceb',
        'secondary-container': '#dfdfe2',
        'inverse-surface': '#342f2f',
        'on-tertiary-container': '#a89489',
        secondary: '#5d5e61',
        'tertiary-fixed-dim': '#d8c2b6',
        'inverse-primary': '#e9bcbc',
        'surface-bright': '#fff8f7',
        'surface-container-low': '#faf2f1',
        'on-tertiary-fixed': '#251912',
        'on-error': '#ffffff',
        'on-primary-container': '#b78e8e',
        'surface-dim': '#e0d8d7',
        'on-primary-fixed-variant': '#5f3e3f',
        'primary-container': '#000000',
        'secondary-fixed-dim': '#c5c6c9',
        'surface-tint': '#795556',
        surface: '#fff8f7',
        'primary-fixed': '#ffdada',
        'on-background': '#1e1b1b',
        'on-primary': '#ffffff',
        tertiary: '#251911',
        'surface-variant': '#e9e1e0',
        'on-secondary': '#ffffff',
        'surface-container-lowest': '#ffffff',
        'on-secondary-fixed': '#191c1e',
        'surface-container-highest': '#e9e1e0',
        background: '#fff8f7',
        'primary-fixed-dim': '#e9bcbc',
        'on-secondary-fixed-variant': '#454749',
        'on-secondary-container': '#616365',
        'tertiary-container': '#3b2d25',
        'on-tertiary-fixed-variant': '#53443b',
        'on-surface': '#1e1b1b',
        'surface-container-high': '#efe6e6',
        'tertiary-fixed': '#f5ded2',
        'error-container': '#ffdad6',
        error: '#ba1a1a',
        'outline-variant': '#d4c3c2',
        'on-primary-fixed': '#2d1415',
        'secondary-fixed': '#e2e2e4',
        outline: '#827474',
        'inverse-on-surface': '#f8efee',
        'on-surface-variant': '#504444',
        primary: '#2d1415',
        'warm-ivory': '#F3E8DF',
        'soft-blush': '#E8D1C5',
        'charcoal-grey': '#2d1415',
        'deep-cocoa': '#452829',
        'brand-bg': '#F3E8DF',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'margin-mobile': '20px',
        'margin-desktop': '64px',
        gutter: '24px',
        'section-gap': '120px',
        'container-max': '1280px',
        unit: '8px',
      },
      maxWidth: {
        'container-max': '1280px',
      },
      fontFamily: {
        'body-md': ['"Hanken Grotesk"', 'sans-serif'],
        'label-sm': ['"Hanken Grotesk"', 'sans-serif'],
        'headline-lg-mobile': ['Montserrat', 'sans-serif'],
        'headline-md': ['Montserrat', 'sans-serif'],
        'body-lg': ['"Hanken Grotesk"', 'sans-serif'],
        'display-lg': ['Montserrat', 'sans-serif'],
        'headline-lg': ['Montserrat', 'sans-serif'],
        'label-caps': ['"Hanken Grotesk"', 'sans-serif'],
      },
      fontSize: {
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-sm': ['13px', { lineHeight: '18px', fontWeight: '500' }],
        'headline-lg-mobile': ['32px', { lineHeight: '40px', fontWeight: '500' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '500' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'display-lg': [
          '64px',
          { lineHeight: '72px', letterSpacing: '-0.02em', fontWeight: '600' },
        ],
        'headline-lg': [
          '40px',
          { lineHeight: '48px', letterSpacing: '-0.01em', fontWeight: '500' },
        ],
        'label-caps': [
          '12px',
          { lineHeight: '16px', letterSpacing: '0.1em', fontWeight: '600' },
        ],
      },
    },
  },
  plugins: [],
} satisfies Config
